import type {Metadata} from "next";
import Navbar from "@/app/Navbar";
import {melete} from "./font"
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={melete.variable}
        >
        <div className="flex justify-between items-center min-h-screen">
            <Navbar/>
            {children}
            <div/>
        </div>

        </body>
        </html>
    )
        ;
}
