import type {Metadata} from "next";
import Navbar from "@/app/Navbar";
import {melete} from "./font"
import "./globals.css";
import Galaxy from "@/components/ui/Galaxy";
import React from "react";

export const metadata: Metadata = {
    title: "SpaceXplore",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={melete.variable}>
        <div className="relative min-h-screen overflow-hidden">
            <div className="absolute inset-0 z-0 pointer-events-none">
                <Galaxy
                    mouseRepulsion={true}
                    mouseInteraction={true}
                    density={1.5}
                    glowIntensity={0.2}
                    saturation={0.4}
                    hueShift={100}
                />
            </div>
            <div className="relative z-10 flex min-h-screen">
                <aside className={"fixed left-0 top-1/2 -translate-y-1/2 z-50"}>
                    <Navbar/>
                </aside>
                <main className="flex-1 ">
                    {children}
                </main>

            </div>
        </div>
        </body>
        </html>
    );
}
